style: add missing spinners to `flox {upgrade,push}`
flox/flox pull request #1112
Opened 2024-03-04 14:52 UTC by ysndr

2024-03-04 19:23 UTC, mkenigs requested changes
nonblocking: we should add one for the first half of `update` too (there's one for the scrape, but not bumping and locking)

2024-03-04 19:23 UTC, mkenigs commented on cli/flox/src/commands/environment.rs
> +                    message: "Pudhing updates to FloxHub...",
```suggestion
                    message: "Pushing updates to FloxHub...",
```

2024-03-04 19:23 UTC, mkenigs commented on cli/flox/src/commands/environment.rs
> +            message: "Upgrading packages and verifying environment...",
nonblocking
```suggestion
            message: "Upgrading packages...",
```

2024-03-05 16:43 UTC, ysndr commented on cli/flox/src/commands/environment.rs
> +                    message: "Pudhing updates to FloxHub...",
🍮

2024-03-05 17:59 UTC, mkenigs approved these changes

2024-03-05 17:59 UTC, mkenigs commented on cli/flox/src/commands/environment.rs
> +                }
nonblocking: I think we should have one on `LockedManifest::update_global_manifest(&flox, self.inputs)` as well

2024-03-06 15:47 UTC, mkenigs approved these changes

2024-03-06 16:12 UTC, merged