fix: handle project paths that contain spaces
flox/flox pull request #1277
Opened 2024-04-04 23:59 UTC by zmitchell

## Proposed Changes

## Release Notes

2024-04-05 14:38 UTC, ysndr commented
`find` might not exist, I think the reason we didn't use it before was to ensure we stick as closely to "bare shell"/"posix shell" as possible.

If we use `find` we need to bundle it into the environment.

2024-04-08 19:33 UTC, mkenigs commented
I would vote using shell over bundling find

2024-04-09 14:50 UTC, limeytexan requested changes

2024-04-09 14:50 UTC, limeytexan commented on pkgdb/src/buildenv/realise.cc
> +  done < <(find "$FLOX_ENV/etc/profile.d" -name '*.sh' -print0)
This introduces a dependency on `find` and correspondingly the `findutils` package which is not currently included in the closure. So we either need to fix that or we can take the simpler approach of doing something like this:
```
if [ -d "$FLOX_ENV/etc/profile.d" ]; then
  declare -a _prof_scripts;
  _prof_scripts=( $(
    cd "$FLOX_ENV/etc/profile.d";
    shopt -s nullglob;
    echo *.sh;
  ) );
  for p in "${_prof_scripts[@]}"; do . "$FLOX_ENV/etc/profile.d/$p"; done
  unset _prof_scripts;
fi
```
_(FWIW I've tested that this works.)_

Thanks.

2024-04-10 16:27 UTC, limeytexan commented on pkgdb/src/buildenv/realise.cc
> +  done < <(find "$FLOX_ENV/etc/profile.d" -name '*.sh' -print0)
```suggestion
  declare -a _prof_scripts;
  _prof_scripts=( $(
    cd "$FLOX_ENV/etc/profile.d";
    shopt -s nullglob;
    echo *.sh;
  ) );
  for p in "${_prof_scripts[@]}"; do . "$FLOX_ENV/etc/profile.d/$p"; done
  unset _prof_scripts;
```

2024-04-10 16:27 UTC, limeytexan commented on pkgdb/src/buildenv/realise.cc
> +  done < <(find "$FLOX_ENV/etc/profile.d" -name '*.sh' -print0)
```suggestion
  declare -a _prof_scripts;
  _prof_scripts=( $(
    cd "$FLOX_ENV/etc/profile.d";
    shopt -s nullglob;
    echo *.sh;
  ) );
  for p in "${_prof_scripts[@]}"; do . "$FLOX_ENV/etc/profile.d/$p"; done
  unset _prof_scripts;
```

2024-04-10 16:31 UTC, limeytexan commented on pkgdb/src/buildenv/realise.cc
> +    shopt -s nullglob;
```suggestion
```

Oops ... that was a cut & paste mistake on my part - we don't want to introduce the use of `shopt` when it wasn't there originally.

2024-04-10 17:22 UTC, mkenigs approved these changes
This will still fail if the profile script has a space in its name, right?

2024-04-10 18:53 UTC, zmitchell commented
I believe so, but we control those names so I think it's less of a concern. I still think `find` is more robust, but I don't mind the current solution.

2024-04-10 21:35 UTC, limeytexan approved these changes
Tests pass, looks good! Thanks @zmitchell

2024-04-10 21:38 UTC, limeytexan commented
> This will still fail if the profile script has a space in its name, right?

Yes, but as Zach points out _we_ are in control over those script names and can ensure that they do not contain spaces.

2024-04-10 21:58 UTC, merged