Draft: test message output from pull
flox/flox pull request #1348
Opened 2024-04-22 09:46 UTC by dcarley

## Proposed Changes

**refactor: wip Test handle_pull_result messages**

I've tried using an enum because we need to know the action and content
of the message. We don't have the emoji formatting though because that's
applied later.

Things I'm unsure about:

- using String when the existing methods use a trait?
- not able to do partial matches on the contents
- there are some intermediate warnings that aren't captured

An alternative could be to construct something like a logger that will
accept a different output buffer for the tests. It's a more invasive
change though.

**chore: wip Additional test for pull errors**

I haven't figured out how to invoke the right branch of the code from
the tests yet.

## Release Notes

N/A

2024-04-22 10:27 UTC, ysndr requested changes

2024-04-22 10:27 UTC, ysndr commented on cli/flox/src/commands/pull.rs
> +    ) -> Result<message::Action, anyhow::Error> {
`anyhow::Result` defaults to `anyhow::Error` as the error variant.

```suggestion
    ) -> Result<message::Action> {
```

2024-04-22 10:27 UTC, ysndr commented on cli/flox/src/utils/message.rs
> +    pub fn print(self) {
print can act on a reference alone, no need to move (and drop) the object.

(`v` will be &String, which implements `Display`)

```suggestion
    pub fn print(&self) {
```

2024-04-22 10:27 UTC, ysndr commented on cli/flox/src/commands/pull.rs
> +                        Ok(message::Action::Warning(message_with_warning))
```suggestion
                        Ok(message::Action::Created(message_with_warning))
```

2024-04-22 10:27 UTC, ysndr commented on cli/flox/src/commands/pull.rs
> +                        Ok(message::Action::Warning(message_with_warning))
i know it says warning, not sure if changing the message type was intentional though

2024-04-24 16:13 UTC, dcarley commented
We discussed some other options in https://flox-dev.slack.com/archives/C05P6A5J6U8/p1713779412179789 and ultimately decided to punt on this for now but may want to revisit when extending the logic in https://github.com/flox/flox/issues/1226

2024-04-24 16:13 UTC, closed without merging