fix: Show a helpful error when a managed environment has been deleted
flox/flox pull request #1638
Opened 2024-06-14 22:27 UTC by nicklewis

Previously, we showed a generic failure message when the upstream 
environment was deleted. We now handle that case and show a message 
indicating what's happened and instructing the user how to restore the 
environment.

This also changes the way we handle EnvironmentSelectErrors. We now 
include a check for EnvironmentSelectError in main() alongside the other error
handler, and handle the EnvironmentSelectError::Environment variant the same as
ordinary EnvironmentErrors.

2024-06-14 22:29 UTC, nicklewis commented
There are probably some tests to add for this, but here it is for review at least.

2024-06-17 13:22 UTC, jennymahmoudi requested changes
For the message itself, can you update it to:

> Run 'flox push' to restore the environment to FloxHub.

Note the single quotes instead of backticks (style guide).

2024-06-17 22:47 UTC, nicklewis commented
Updated to use single quotes and to only show the message if you're the owner of the environment.

2024-06-18 13:31 UTC, jennymahmoudi approved these changes

2024-06-18 13:35 UTC, ysndr approved these changes
Error handling is spread rather broadly and apparently we have some duplication to deal with through explicit handling not removed yet or parallel efforts in here and #1632.

Functionally: lgtm
still worth a greenkeeping ticket to deal with the handling duplications.

2024-06-18 17:24 UTC, nicklewis commented on cli/flox/src/main.rs
> +            if let Some(EnvironmentSelectError::Environment(e)) =
Updated

2024-06-18 19:38 UTC, zmitchell approved these changes

2024-06-18 19:38 UTC, zmitchell commented on cli/flox-rust-sdk/src/models/environment/managed_environment.rs
> +    UpstreamNotFound(EnvironmentRef, String, Option<String>),
Suggestion: make this a struct variant with named fields, it's unclear what the `Option<String>` is supposed to represent from looking at this.

Something like this
```rust
#[error("environment '{name}' does not exist at upstream '{upstream}'")]
UpstreamNotFound {
    name: EnvironmentRef,
    upstream: String,
    whatever_this_one_is: Option<String>,
}
```

2024-06-18 21:05 UTC, zmitchell approved these changes

2024-06-18 21:34 UTC, merged