ci: run integ-tests in parallel
flox/flox pull request #2111
Opened 2024-09-20 13:43 UTC by ysndr

## [ci: run integ-tests in parallel](https://github.com/flox/flox/commit/eb8d816253f6cdc536285857a8e52da2ad69d83d)

* Run bats tests with `--jobs $(nproc)`.
* Disallow parallel runs across files
* Do not run `activate` tests in parallel
These tests break frequently, likely do to $HOME/$USER discrepancy.## Proposed Changes

## [refactor: set euid user earlier](https://github.com/flox/flox/commit/7c78b0cbce756b34c3709155cf1539d90a75d1c2) 

Run the `set_user` function earlier to allow `config` to read from the right user.

2024-09-20 14:08 UTC, ysndr commented on .github/workflows/ci.yml
> +            --jobs "$(nproc)" \
Of course not a standard in macOS runners :)
```suggestion
            --jobs 4 \
```

2024-09-20 15:55 UTC, bryanhonof approved these changes
Bats and GitHub workflow looks good to me.

2024-09-20 18:20 UTC, tomberek commented
Very nice: [11m 52s](https://github.com/flox/flox/actions/runs/10960799294/usage)

2024-09-20 22:22 UTC, mkenigs requested changes
Nice! Yeah I think we need to use something like `watchdog_pids_called_with_arg` in `wait_for_watchdogs` with a test specific arg.

I think we can also remove the `wait_for_watchdogs` in `common_test_teardown`

2024-09-23 11:04 UTC, dcarley approved these changes

2024-09-23 11:04 UTC, dcarley commented on .github/workflows/ci.yml
I'm kinda surprised that it hasn't made more difference to the job times but 1~2mins is still worth it 👍🏻

2024-09-23 11:23 UTC, bryanhonof commented on .github/workflows/ci.yml
I don't think it made much of a difference because there are some tests that just take a while to run, whilst the other finish relatively quickly.
So, the quick ones still finish quickly, but since they're not running on different "jobs", it's difficult to see the real impact.
I've tried integrating our test suite with [Buildkite's test suite offering](https://buildkite.com/test-analytics), which could give us more insight into which tests are really taking a lot of time, and which are flaky, etc.

2024-09-23 11:24 UTC, bryanhonof commented on .github/workflows/ci.yml
> +            --no-parallelize-across-files
I don't see why not, but note that `flox-cli-tests` is run on our own hardware. So there might be some inconsistencies there.

2024-09-23 14:55 UTC, ysndr commented on .github/workflows/ci.yml
> +            --no-parallelize-across-files
I think we shouldn't add an arbitrary parallel/jobs arg in the test runner by default.
We may add a flag to override it but its still surprising IMO

2024-09-23 14:56 UTC, ysndr commented on .github/workflows/ci.yml
its also not parallelizing _everything_ only within files.
So multiple long running tests in separate files will just add up

2024-09-23 15:07 UTC, ysndr commented
> I think we need to use something like `watchdog_pids_called_with_arg` in `wait_for_watchdogs` with a test specific arg.

aren't we already doing that by filtering by FLOX_DATA_DIR, which is test specific (through `setup_isolated_flox` in `setup`)?

https://github.com/flox/flox/blob/5b3e4eb0da7e3f11363e98a1ac5f15253ca2d88f/cli/tests/test_support.bash#L186-L191

2024-09-23 15:45 UTC, dcarley commented on .github/workflows/ci.yml
> +            --no-parallelize-across-files
Can you describe why?

I think it's more surprising that the tests run differently in this one context than all the others. It increases the chances that the tests pass locally and then fail after waiting for CI, or fail in the "Matrix: dev" jobs and not the "Matrix: remote" jobs.

2024-09-23 17:00 UTC, mkenigs commented
> aren't we already doing that by filtering by FLOX_DATA_DIR, which is test specific (through `setup_isolated_flox` in `setup`)?

Oh yeah I guess so. If we're going to leave that implicit, I really think we should remove `wait_for_watchdogs` from `common_test_teardown`. And we should add a comment before `wait_for_watchdogs` in services.bats that it's okay to call since we've used `setup_isolated_flox`

Side note: we can't use services in any test file other than services.bats, which we should probably enforce.

2024-09-23 17:10 UTC, mkenigs commented on .github/workflows/ci.yml
> +            --no-parallelize-across-files
I would also be inclined to move it to `flox-cli-tests`

2024-09-23 17:14 UTC, mkenigs approved these changes

2024-09-23 18:07 UTC, merged