feat: use 'now' as the creation timestamp
flox/flox pull request #2128
Opened 2024-09-24 17:33 UTC by tomberek

## Proposed Changes

Use "now" as the timestamp.

## Release Notes
- use a reasonable timestamp

2024-09-24 17:52 UTC, mkenigs requested changes
This is setting the time on every single layer, which means if you `flox containerize -o - | podman load` two times in a row we get zero layer re-use. We need to set the `Created` field for the container but not the `created` fields for all of the layers

```
[
     {
          "Id": "c66f0a8fac949f32692ffc5ff80a98dfe6df7d0308d1b9aaedbeaee84e2df1f8",
          "Digest": "sha256:2fa22d2b84ddbb25f6f095205f3d1ad57cab24c4a0ecb4af7af2080b2424f015",
          "RepoTags": [
               "localhost/flox:wd89rs8m40zl11brmq9scffycdnjyr3q"
          ],
          "RepoDigests": [
               "localhost/flox@sha256:2fa22d2b84ddbb25f6f095205f3d1ad57cab24c4a0ecb4af7af2080b2424f015"
          ],
          "Parent": "",
          "Comment": "",
          "Created": "2024-09-24T17:47:04.369877Z",
          "Config": {
               "Env": [
                    "FLOX_ENV=/nix/store/jf3fblvzlpr0clqhsvqiqj3sk3x5pa7j-environment",
                    "FLOX_PROMPT_COLOR_1=99",
                    "FLOX_PROMPT_COLOR_2=141",
                    "FLOX_PROMPT_ENVIRONMENTS=floxenv",
                    "FLOX_SHELL=/nix/store/bh6w9sbfz2m5w1bd4cg2ndw1s66agkfd-bash-interactive-5.2p26/bin/bash",
                    "FLOX_SOURCED_FROM_SHELL_RC=1",
                    "_FLOX_ACTIVE_ENVIRONMENTS=[]",
                    "_FLOX_FORCE_INTERACTIVE=1"
               ],
               "Entrypoint": [
                    "/nix/store/jf3fblvzlpr0clqhsvqiqj3sk3x5pa7j-environment/activate"
               ]
          },
          "Version": "",
          "Author": "",
          "Architecture": "amd64",
          "Os": "linux",
          "Size": 250410048,
          "VirtualSize": 250410048,
          "GraphDriver": {
               "Name": "overlay",
               "Data": {
                    "LowerDir": "/home/matthew/.local/share/containers/storage/overlay/200cac52f0d06fcae9e5e0bb90e597b9b3c7387bfa95d4827a32860170719d8c/diff:/home/matthew/.local/share/containers/storage/overlay/57694b7d3b3e54ca4047ba7bf5a2dfea49086da890ac202a9ec0336d10ca7857/diff:/home/matthew/.local/share/containers/storage/overlay/681cf6a15ad8eb02ea483d12ea544e7daaa36e1eb340e22ccaece954d230fb11/diff:/home/matthew/.local/share/containers/storage/overlay/a79ce4937618b224371807a2745a1af21438397796ce50dd6ed966c4d978a89e/diff:/home/matthew/.local/share/containers/storage/overlay/980e24b9950238f5e978dac36cc2ffe11ea4bc8c3230d925ea9dbb3fe4faaa73/diff:/home/matthew/.local/share/containers/storage/overlay/9927a1c7c1e78d2c41804bd56ed8548b806476376bc745aa20889109295c240d/diff:/home/matthew/.local/share/containers/storage/overlay/68ca4c5e8c30003806ccfd15190f7f8b82b39fac1ce036428e2b7ad25edb7442/diff:/home/matthew/.local/share/containers/storage/overlay/0ff6db465408fb84ad9394e9ade6c97d292118cf791c76a35309a43ee1e9e1a1/diff:/home/matthew/.local/share/containers/storage/overlay/91960f52e73e801c685b8dcde6ead63783c6eb65fa150a8dab3e9f825b827381/diff:/home/matthew/.local/share/containers/storage/overlay/e36ac986d8b88c1b791484d77fdd76d16f1b8211d26f5cfb35a821e4038fd042/diff:/home/matthew/.local/share/containers/storage/overlay/d1fa421a74f3a2e3b33c510bb94ce3135c08f46b2f77aab96189c322ecb1367b/diff:/home/matthew/.local/share/containers/storage/overlay/6d80dd2be5cdcf02ab0ce2609977737ab6c4c7b2a4632f1e7212c2bfe825ee3a/diff:/home/matthew/.local/share/containers/storage/overlay/6cc4d8edc100de9af8368d80efc2770270cedb439594b66eaeead06889b0b6b0/diff:/home/matthew/.local/share/containers/storage/overlay/9a944e21f73057f7f45ac5561013453db2ce103b2bbf88c2ae1e605c54ba1b04/diff:/home/matthew/.local/share/containers/storage/overlay/692711d1f9963ed560a0b7bf66461a457057c92285fd74a6021d05dfd01414f4/diff:/home/matthew/.local/share/containers/storage/overlay/0a0758b5d74ef5d6bec99a23d70eb4fe83c0bbd8594d8a94cf677a0c7e2c2b87/diff:/home/matthew/.local/share/containers/storage/overlay/35870be25f8346bed2d8599923a9046251249c432fff7c1f9ebe3984b28acedf/diff:/home/matthew/.local/share/containers/storage/overlay/6c05f89fcdc0cb12ecfe3d511de8732fe79e06d26314d94a36a4df65187ca110/diff:/home/matthew/.local/share/containers/storage/overlay/634e4e56235994638a3baac2da86c1ea5fc22ecf7169f36093555587be562e64/diff:/home/matthew/.local/share/containers/storage/overlay/d4252459d489ec9583378f7fdbb2666702c5fb1f3a56f28a81e07becfbec48d8/diff:/home/matthew/.local/share/containers/storage/overlay/260cb15510153109ed11fc1805ed74dc5acfd385c19912ff3fd7a3b321e5cd86/diff:/home/matthew/.local/share/containers/storage/overlay/24f886b656c4d0d8cd22520d2961597dc13e82b30a3afa1378d83f9562868c92/diff:/home/matthew/.local/share/containers/storage/overlay/31af23356235874ff6cf7c57ea5b6b72da3ed52c3397a308637e966e3b5424a9/diff:/home/matthew/.local/share/containers/storage/overlay/595e7504241d3d6702dbdab98bf16d82019668b63fd0014e23ec9cccff46f6e7/diff:/home/matthew/.local/share/containers/storage/overlay/39e6ab348f2eda18526c9987baf4cdd7cf91524c2da6abff2765d634f9101276/diff:/home/matthew/.local/share/containers/storage/overlay/713d4135d597d646698a1bf579b2cb7282a9f9b320e31d515a0123540cabc946/diff:/home/matthew/.local/share/containers/storage/overlay/1d9e5b338c47f43f97bd317d3117d39c0f94f067771348fee5eda21713cd6cfe/diff:/home/matthew/.local/share/containers/storage/overlay/bb9b29a3c2b4b0be74e74f7a672d4a23703eea5cfea98c3c2d46581366e7cc67/diff:/home/matthew/.local/share/containers/storage/overlay/df1df50f3022f589552ab3592611f39491b5e32a9aa299ab61176389e00f3a7e/diff:/home/matthew/.local/share/containers/storage/overlay/95106eb2440794fe3b3359052421a077068416190873e86832270e6da71ab265/diff:/home/matthew/.local/share/containers/storage/overlay/711cfc612f4089a45a9ce91513cc97912579a16be89598a894c1c65904b5f59a/diff:/home/matthew/.local/share/containers/storage/overlay/848d34e97af3814fdf8d5ed591a5f5a27eb341afb9222440bee499e1e17ac91f/diff:/home/matthew/.local/share/containers/storage/overlay/c08f4aa09f25c17e9b63bdeae8f5f84e29298abbe371d99f42afcad07840e157/diff:/home/matthew/.local/share/containers/storage/overlay/f88e82b1c30079b1978463068f3d971c6fb1caad574b7c7906a97999b92cd305/diff:/home/matthew/.local/share/containers/storage/overlay/925ce7d8ddf341263ce698b809247b08b3a7fe1df29cb969abe49f74700c090a/diff:/home/matthew/.local/share/containers/storage/overlay/aa8a6426964a81c7ec8659089c1aeb92b691b4533a8f3f6d8429425ecf187084/diff:/home/matthew/.local/share/containers/storage/overlay/a9214c50386c8dd41747ac2bbc9d941681000972f0826d7a2f485a37b8b1b97d/diff:/home/matthew/.local/share/containers/storage/overlay/ad2283d6f7d9e7462d0929d19030bc248cd2f2f27407679f98025d2a3cb0c3e9/diff:/home/matthew/.local/share/containers/storage/overlay/27176379990faa4480202b16993c5892812ca97ad6e010e83bb83d8af720e661/diff:/home/matthew/.local/share/containers/storage/overlay/d29267d91a1d5ee358df82763543805ca45a4e344dfe250954f0e1adf89544f9/diff:/home/matthew/.local/share/containers/storage/overlay/e7a67527b6e3921196d97b9a4d0608b42e64a55fadef99e3b24483b4ebc4169a/diff:/home/matthew/.local/share/containers/storage/overlay/a59502520b82f5ec3cdb7fb51693729ded9312f57f82231177494d78d4437456/diff:/home/matthew/.local/share/containers/storage/overlay/9897f0706b1d97dc67a8c7b3e62949ee70d71e4932d0d6b2b3ad1dfbd1c7a4ed/diff:/home/matthew/.local/share/containers/storage/overlay/e0a30b6b770ea2e7a5533b34ec8d93d9c9ea6de8daa445213e1735ba3243c0d8/diff:/home/matthew/.local/share/containers/storage/overlay/25f4c83622a01ce229e7a559bd6aa16cd71ca81c9a23a863de2ef042dc6eddef/diff:/home/matthew/.local/share/containers/storage/overlay/7f677da2223d4c1757ab947f25b9db6e9d4774a865a6b5185b0c6dc0b43aec6e/diff:/home/matthew/.local/share/containers/storage/overlay/f2e7ce723cee8c04bd58e4642a3fef3d7e3f059073e7a7e07a2506a199249315/diff:/home/matthew/.local/share/containers/storage/overlay/598ef1201c33bded5b176a10f1cf838e2e64f9bbb1a44a36fd4e01c07d7ab5bf/diff:/home/matthew/.local/share/containers/storage/overlay/ab09fc4d7a06ddd5e460b05f80dce15c7788667e76d9bea6e6bf74db155315f5/diff:/home/matthew/.local/share/containers/storage/overlay/54290a543f31af533c004772a6b9da1f6a8cb02d38450a1d2f7850e2251794e8/diff: [...]

2024-09-24 20:33 UTC, bryanhonof commented
@mkenigs I doubt it. The actual contents of the layers should be stored in a content-addressed manner. The `Created` field you see there, is to just show the "history" of the image in a somewhat human-readable form, what happened to it over time.  It shouldn't affect the layer contents. [From the OCI spec:](https://github.com/opencontainers/image-spec/blob/da92727e9c8761ec087890466b8756b755aefd37/config.md)

```
- history array of objects, OPTIONAL

Describes the history of each layer.
```

2024-09-24 20:47 UTC, tomberek commented
The layers are re-used. You see them reloaded in the streaming load because they load them in, but you'll notice that the layer hashes are the same. The outermost manifest annotation does change..... i'll take a closer look tomorrow.

2024-09-24 21:16 UTC, bryanhonof commented
@tomberek It seems like the layers do change...
So I'm guessing something funky is happening in `dockerTools.streamLayeredImage`.

```console
$ flox --version
1.3.2-gbb4fd52
$ flox list
hello: hello (2.12.1)
$ date
Tue Sep 24 09:12:05 PM UTC 2024
$ flox containerize
Cut for brevity...
$ skopeo inspect tarball:$PWD/flox-containerize-reproducability-tests-container.tar
{
    "Digest": "sha256:c009e86b24c1157b31d7624bb0b74e4186723b20138bc1f44e42ecdf4ce49124",
    "RepoTags": [],
    "Created": "2024-09-24T21:12:36.216377702Z",
    "DockerVersion": "",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:b5dcb281389bf95dff843ddfb90939897fc680fad5076cb9b92e532a4fb83aeb"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.oci.image.layer.v1.tar",
            "Digest": "sha256:b5dcb281389bf95dff843ddfb90939897fc680fad5076cb9b92e532a4fb83aeb",
            "Size": 284026880,
            "Annotations": null
        }
    ],
    "Env": null
}
$ date
Tue Sep 24 09:14:13 PM UTC 2024
$ flox containerize
Cut for brevity...
$ skopeo inspect tarball:$PWD/flox-containerize-reproducability-tests-container.tar
{
    "Digest": "sha256:f0c2c7e34b5a5d98d79590c6e50722b12ac339acd914ecfc4cd7f8211789addd",
    "RepoTags": [],
    "Created": "2024-09-24T21:14:24.079503738Z",
    "DockerVersion": "",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:36e305700d4eb45da3eb6731f00a738bb9c6c9de644713902b3d7cf5efd752ea"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.oci.image.layer.v1.tar",
            "Digest": "sha256:36e305700d4eb45da3eb6731f00a738bb9c6c9de644713902b3d7cf5efd752ea",
            "Size": 284026880,
            "Annotations": null
        }
    ],
    "Env": null
}
```

2024-09-27 15:52 UTC, tomberek commented
Upstream PR is merged... waiting for it to be available in flox/nixpkgs, and then we can do a bump

2024-10-01 15:19 UTC, tomberek commented
@flox/cli When do we plan to do a lock bump? (or more precisely, to bump the bundled Nixpkgs used by pkgdb?)

2024-10-01 15:25 UTC, ysndr commented
@tomberek if that's simply updating nixpkgs we can probably do that any time (at least while upstream nix is still 2.18)

https://github.com/flox/flox/blob/52df88e4cc2454d52b78d0aa2f183e779da57f0e/pkgs/flox-pkgdb/default.nix#L79-L85

2024-10-01 15:50 UTC, tomberek commented
okay. still need to wait for it to reach stable: https://github.com/flox/nixpkgs/tree/stable/pkgs/build-support/docker

2024-10-22 05:10 UTC, tomberek commented
Update: still blocked. Upstream changes have not yet made it to [stable](https://github.com/flox/nixpkgs/tree/stable/pkgs/build-support/docker)

Options:
1. Use non-stable branch of flox/nixpkgs [here](https://github.com/flox/flox/blob/main/flake.nix#L23). This would revert the intention of [this commit](https://github.com/flox/flox/commit/d732cb871eab2c40585346bafe9b535fe078e04a).
2. Vendor a minimal nixpkgs or dockerTools into flox. Would require vendoring the whole folder and adding special-cases to including it into the final closure, then removing it in a few weeks.
3. Add another reference to Nixpkgs into pkgdb. Not recommended due to bloat and keeping track of a third Nixpkgs rev.
4. Investigate if floxbox has been delayed: Nope. Service looks healthy.
5. Wait for stable to contain upstream changes. Last update to stable occurred on Oct 05 with a Sep 23 Nixpkgs commit date. Expect the next bump to stable to [occur on Nov 03](https://github.com/flox/floxbox/blob/main/nixos-modules/update-nixpkgs.sh#L93C5-L94C40) based on the monthly update cycle.

This is a quality-of-life improvement, but does not block other work.

2024-11-04 17:44 UTC, bryanhonof approved these changes

2024-11-04 19:23 UTC, mkenigs commented
I think we need to do https://github.com/flox/flox/pull/2316 first

2024-11-04 19:24 UTC, tomberek commented
> I think we need to do #2316 first

I was adding that to this... but if 2316 is already on its way... I'll wait and rebase as-needed.

2024-11-04 23:58 UTC, mkenigs requested changes
Using `podman image inspect` I think this is still putting the timestamp on every layer, and we need that to be epoch

2024-11-05 16:25 UTC, tomberek commented
The layer hashes are stable.
```
podman image inspect localhost/flox:latest | jq '.[].RootFS.Layers[]' | head -n60 | sha256sum
b019c8eb1778457215001ee312ad215820c7ff7b4f4f8e13ae48190db2ffd62b  -
```
The json of the top-level manifest still records the time, but I don't think that is at the layer level.

2024-11-05 18:43 UTC, mkenigs approved these changes
You're right my bad, `History` still records the time for each layer, but that doesn't affect the hashes

2024-11-05 23:22 UTC, merged