feat: use flox-activations to store env files
flox/flox pull request #2256
Opened 2024-10-22 00:18 UTC by mkenigs

Use `flox-activations start-or-attach` and `flox-activations set-ready`
to store environment variable diffs rather than _add_env and _del_env.

This introduces attaching; activations of an environment that are
already active don't re-run hooks.

Notes:
- _FLOX_ACTIVATE_FORCE_REACTIVATE was used to force the activation
  script to re-run start because the activation script couldn't detect
  when the environment store path had changed. Now that start-or-attach
  is aware of the store_path for an environment, this isn't necessary.
- Previously we would run start.bash without capturing _start_env or
  _end_env because we knew nobody would attach. That's no longer true.

## Release Notes

When an environment is activated multiple times before all activations of the environment exit, the environment's hook is only run once by the first activation. Subsequent activations set environment variables set by the hook, but they don't actually re-run commands in the hook.

2024-10-22 10:59 UTC, limeytexan commented
> Use flox-activations start-or-attach and flox-activations set-ready to store environment variable diffs rather than _add_env and _del_env.

@mkenigs you mean "to store environment variable _**snapshots**_" rather than diffs, right? The idea is to capture the `env{0,1,2}` snapshots and then be able to calculate the diffs between the stages on demand as you need them.

2024-10-23 00:07 UTC, mkenigs commented
> @mkenigs you mean "to store environment variable _**snapshots**_" rather than diffs, right? The idea is to capture the `env{0,1,2}` snapshots and then be able to calculate the diffs between the stages on demand as you need them.

Yep I'll reword

2024-10-23 22:08 UTC, mkenigs commented
@dcarley I rebased against main, dropping https://github.com/flox/flox/pull/2256/commits/dee35c0a4c67f13f6eedf2f83dfc1ea94e964730 since that was merged in another PR

2024-10-24 19:58 UTC, mkenigs commented
Rebased again

2024-10-25 20:02 UTC, zmitchell requested changes

2024-10-25 20:23 UTC, mkenigs commented on assets/activation-scripts/activate
> +to_eval="$($_flox_activations start-or-attach --pid "$$" --flox-env "$_FLOX_ENV" --store-path "$_FLOX_ACTIVATE_STORE_PATH")"
Good catch

2024-10-25 20:23 UTC, mkenigs commented on cli/flox/src/commands/activate.rs
> +            panic!(
Fixed

2024-10-25 20:24 UTC, zmitchell approved these changes

2024-10-25 22:19 UTC, mkenigs commented
> > @mkenigs you mean "to store environment variable _**snapshots**_" rather than diffs, right? The idea is to capture the `env{0,1,2}` snapshots and then be able to calculate the diffs between the stages on demand as you need them.
> 
> Yep I'll reword

Well actually I stored both the diffs and the snapshots for now, we can tweak that in the future though

2024-10-25 22:55 UTC, merged