refactor: move activations crate to flox-core
flox/flox pull request #2275
Opened 2024-10-26 01:42 UTC by mkenigs

flox-watchdog will depend on reading activations.json and its
contents, so move the activations crate to flox-core

## Release Notes

NA

2024-10-26 08:58 UTC, ysndr commented
nit: activations ~crate~ module

2024-10-26 09:11 UTC, ysndr requested changes

2024-10-26 09:11 UTC, ysndr commented on cli/flox-core/src/activations.rs
> +    pub attached_pids: Vec<AttachedPid>,
I'd prefer we keep this private to the struct to go retain its "readonly" / controlled modification property.
If the field is public you'll have to reason about using the `Activation`s methid vs accessing the field explicitly.

2024-10-28 18:57 UTC, zmitchell approved these changes

2024-10-28 19:11 UTC, merged