Comparison: Flox vs Docker vs Homebrew
flox/flox pull request #2556
Opened 2024-12-27 00:11 UTC by Hezam20

## Proposed Changes
This documentation PR explains the difference between Flox, Docker, and Homebrew.

2024-12-28 03:54 UTC, spencergibb commented on README.md
> +# Flox vs Homebre:
Homebrew (missing w)

2024-12-30 17:49 UTC, Hezam20 commented on README.md
> +# Flox vs Homebre:
Thank you!

2025-01-03 00:17 UTC, stahnma requested changes
Hey, thanks for much for this contribution. I've added some comments. I'm not trying to poke holes in your ideas, but want them to be clear and helpful to anybody reading, so did a little more nit-picking than I normally do.

2025-01-03 00:17 UTC, stahnma commented on README.md
> +This document compares **Homebrew** and **Flox**, two popular package managers used in modern development environments. Each has its own strengths and is suited to different use cases. Here's a side-
>This document

The README? Perhaps this section of the document, but if it's doing that, it doesn't have to be called out as it doing that.

2025-01-03 00:17 UTC, stahnma commented on README.md
> +- **Homebrew** is a package manager primarily for macOS. It allows users to easily install, update, and manage software packages with a simple command-line interface. Packages are installed in standa
It uses a FHS under `/opt/homebrew`. That follows the FHS guidelines, but I don't see how that makes it "user-friendly" for macOS users. How does it do that?

2025-01-03 00:17 UTC, stahnma commented on README.md
> +- **Flox** is a cross-platform, purely functional package manager available for multiple operating systems. It isolates packages in their own environments, ensuring reproducibility and conflict-free
What does functional mean in this context for the user?

2025-01-03 00:17 UTC, stahnma commented on README.md
> +- **Homebrew** offers easy version management, allowing users to switch between package versions using the `brew switch` command. This is useful when certain packages depend on specific versions.
> `brew switch`

Error: Unknown command: brew switch

According to stackoverflow this was deprecated in 2020. 

I _think_ the way you can do this with brew today is `brew unlink <package>` and `brew link <package>@<version>`.  However, that is global.

2025-01-03 00:17 UTC, stahnma commented on README.md
> +- **Flox** is highly **customizable** and **extensible**, offering users the ability to define custom package sets, build configurations, and even entire environments. Flox is based on Nix, a functio
Flox is built-upon Nix, not based on it. (that might seem minor, but matters a lot to us).

2025-01-03 00:17 UTC, stahnma commented on README.md
> +- **Homebrew** is simple and easy to use, making it ideal for casual users and those who need a straightforward package management experience. Its primary focus is on usability and quick installation
I would say it's great for single-users on single machines who want one version of software in nearly all cases.

2025-01-06 21:45 UTC, Hezam20 commented on README.md
> +- **Homebrew** is a package manager primarily for macOS. It allows users to easily install, update, and manage software packages with a simple command-line interface. Packages are installed in standa
What I mean by 'user-friendly' is that Homebrew provides a simple, consistent command-line interface that's easy for users to use and doesn't require a complex setup.

I made a small modification—let me know if you'd like any further changes, and I'll be happy to adjust accordingly

2025-01-06 22:01 UTC, Hezam20 commented on README.md
> +- **Flox** is a cross-platform, purely functional package manager available for multiple operating systems. It isolates packages in their own environments, ensuring reproducibility and conflict-free
I read this in [Nix's documentation](https://nixos.org/guides/how-nix-works/) and thought it might be useful to add here. However, it seems to be causing more confusion for the reader.

Do you think adding this would help:

> Being purely functional, Flox treats packages as values built by functions without side effects, and they never change after being built.

2025-01-06 22:04 UTC, Hezam20 commented on README.md
> +- **Homebrew** offers easy version management, allowing users to switch between package versions using the `brew switch` command. This is useful when certain packages depend on specific versions.
Thank you for catching that! I made the changes and decided not to add too many details about Homebrew, what do you think?

2025-01-06 22:06 UTC, Hezam20 commented on README.md
> +- **Homebrew** is simple and easy to use, making it ideal for casual users and those who need a straightforward package management experience. Its primary focus is on usability and quick installation
I made a small modification—let me know if you'd like any further changes, and I'll be happy to adjust accordingly

2025-01-07 22:22 UTC, closed without merging

2025-01-07 22:22 UTC, stahnma commented
I'm not sure this information is really needed in the README directly. Most of this is probably better served by being the docs with more context, nuance and depth. I (and the rest of the team) really like your enthusiasm here and were trying to find a way to fit it with the README, but doesn't quite belong. I apologize for that and I really hope not to discourage you!