feat: use last activated environment
flox/flox pull request #498
Opened 2023-11-30 21:22 UTC by mkenigs

- Keep track of activated environments in FLOX_ACTIVE_ENVIRONMENTS.
- For environment commands, use the last activated environment when not in a directory that contains a .flox.
- Use the parent path of the .flox directory for confirmation messages printed to users.

This is part of https://github.com/flox/flox/issues/359, but it doesn't use last activated environment for search or show, and it doesn't implement handling for when there's an activated environment and a .flox in current directory.

2023-11-30 21:32 UTC, zmitchell commented on crates/flox/src/commands/environment.rs
> +                format!("{prompt_name} {prompt_environments}")
I thought there was something about this in the specs, but I wasn't able to find it. I think just stick with what you have, it's easy to change.

2023-11-30 21:57 UTC, zmitchell requested changes
Mostly looks good to me, but I think you can make the interface a little simpler making `parent_path` return a `PathBuf` instead of a `String`. You can still check whether it contains `:` by doing something like `path.to_str().map(...check for ':').unwrap_or(false)` in the one or two places that you need to treat the path like a string.

I'm not sure if you knew this, but you can set the "check" command that VS Code uses to check your code while you're working on it to `clippy` and it will show you the clippy suggestions while you're working (that's how I work).

2023-11-30 21:57 UTC, zmitchell commented on crates/flox/src/commands/mod.rs
> +    fn open_pointer(
```suggestion
    fn open_env_pointer(
```
Suggestion: "pointer" is a term that has specific meaning in systems languages like C/C++/Rust. If we're going to use the term "environment pointer" we need to make sure that it's unambiguous at the call site which kind of pointer we're talking about.

2023-12-01 08:18 UTC, garbas approved these changes

2023-12-01 13:00 UTC, ysndr requested changes

2023-12-01 16:43 UTC, mkenigs commented on crates/flox/src/commands/environment.rs
> +            });
It would require adding another environment variable to communicate, and I don't think it really gains us much at this point

2023-12-01 17:01 UTC, mkenigs commented on crates/flox/src/commands/environment.rs
>              .env("FLOX_PROMPT_ENVIRONMENTS", flox_prompt_environments)
Fixing

2023-12-01 17:54 UTC, mkenigs commented on crates/flox-rust-sdk/src/models/environment/mod.rs
> +    fn parent_path(&self) -> Result<String, EnvironmentError2>;
Changing to use `PathBuf` and `split_paths`/`join_paths`

2023-12-01 18:04 UTC, mkenigs commented on crates/flox-rust-sdk/src/models/environment/mod.rs
> +}
Fixing

2023-12-01 18:13 UTC, mkenigs commented on crates/flox/src/commands/mod.rs
>      pub fn to_concrete_environment(&self, flox: &Flox) -> Result<ConcreteEnvironment> {
Fixing

2023-12-01 23:02 UTC, merged