feat: scrape rules
flox/flox pull request #689
Opened 2023-12-21 20:34 UTC by aakropotkin

## Proposed Changes

## Release Notes

2023-12-22 22:35 UTC, aakropotkin commented on pkgdb/Makefile
> +.NOTPARALLEL: $(_TEST_LOCKFILES) test-lockfiles test-data
Fixes issue running `make -j tests`

2023-12-22 22:36 UTC, aakropotkin commented on pkgdb/tests/scrape-rules.bats
> +	rules_json='{
```suggestion
       # FIXME: formatting
	rules_json='{
```

2023-12-22 23:13 UTC, aakropotkin commented on pkgdb/tests/search.bats
> +  if [[ -z "${PKGDB_SEARCH_PARAMS_BIN:=$( command -v search-params; )}" ]]; then
```suggestion
  if [ -z "${PKGDB_SEARCH_PARAMS_BIN:=$( command -v search-params; )}" ]; then
```

2023-12-22 23:14 UTC, aakropotkin commented on pkgs/flox-pkgdb/default.nix
> +            PKGDB_IS_SQLITE3_BIN="$REPO_ROOT/pkgdb/tests/is_sqlite3";
@garbas possibly relevant

2023-12-22 23:17 UTC, aakropotkin commented on pkgdb/Makefile
> -VERSION := $(file < $(PKGDB_ROOT)/version)
This avoids an issue where `#include <version>` inside of `boost` can wind up including this file if you are using a non-GNU version of `make`.

2024-01-02 09:07 UTC, ysndr requested changes

2024-01-02 13:04 UTC, aakropotkin commented on pkgdb/Makefile
> +<<<<<<< HEAD
good catch

2024-01-02 13:06 UTC, aakropotkin commented on pkgdb/src/pkgdb/scrape.cc
> +  // TODO: We need to invalidate caches any time we change the rules file.
yes

2024-01-02 13:06 UTC, aakropotkin commented on pkgdb/include/flox/pkgdb/write.hh
> +struct RulesTreeNode
Yeah that's a good point I can get some docs added.

2024-01-02 13:06 UTC, aakropotkin commented on pkgdb/src/pkgdb/rules.json.hh
Yes these are the defaults.

2024-01-02 13:08 UTC, aakropotkin commented on pkgdb/src/pkgdb/write.cc
> +          return SR_DEFAULT;
`SR_DEFAULT` means "run the regular `scrape` checks, but nothing special" - so check `recurseForDerivations` and junk.

`SR_UNSET` is an uninitialized state.

2024-01-02 13:11 UTC, aakropotkin commented on pkgdb/src/pkgdb/write.cc
> +                              + scrapeRuleToString( rule ) + '\'' );
I have always been using ``some doc `keyword'``; it's only in follow up PRs that they're getting changed to `'keyword'` instead.

That convention for quotations is from LISP and most GNU documentation which is where I picked it up.

2024-01-02 13:12 UTC, aakropotkin commented on pkgdb/src/resolver/environment.cc
> +  std::string groupStr = concatStringsSep( " ", ids );
I pulled the definition from `nix` and added it to our `util.hh` file.
Then aligned all invocations of `nix::concatStringsSep( ... )` and `joinWithDelim( ... )` to use _our_ `concatStringsSep( ... )`.

2024-01-02 16:09 UTC, ysndr commented on pkgdb/src/pkgdb/write.cc
> +          return SR_DEFAULT;
is `SR_UNSET` then an error state or handled like default or just ignored basically?

2024-01-08 19:25 UTC, samrose commented
This is an integration test case meant to be used with scrape rules. It probably doesn't work as-is but is a good start


```shell
#! /usr/bin/env bats
# -*- mode: bats; -*-
# ============================================================================ #
#
# `pkgdb scrape --rules' CLI tests.
#
# These tests are meant to test the `pkgdb scrape --rules' CLI command.
#
# ---------------------------------------------------------------------------- #

load setup_suite.bash

# bats file_tags=cli,scrape,scrape-rules,flake

# Set up test environment
setup() {
	export DBPATH="$BATS_FILE_TMPDIR/test.sqlite"
	mkdir -p "$BATS_FILE_TMPDIR"
	# We don't parallelize these to avoid DB sync headaches and to recycle the
	# cache between tests.
	# Nonetheless this file makes an effort to avoid depending on past state in
	# such a way that would make it difficult to eventually parallelize in
	# the future.
	export BATS_NO_PARALLELIZE_WITHIN_FILE=true

	# Define rules.json content
	rules_json='{
				"allowRecursive": [
					[
						"legacyPackages",
						null,
						"darwin"
					]
				],
				"allowPackage": [
					[
						"legacyPackages",
						null,
						"python310Packages",
						"pip"
					],
					[
						"legacyPackages",
						null,
						"python310Packages",
						"django"
					]
				],
				"disallowRecursive": [
					[
						"legacyPackages",
						null,
						"python310Packages"
					],
					[
						"legacyPackages",
						null,
						"emacsPackages"
					],
					[
						"legacyPackages",
						null,
						"vimPlugins"
					]
				],
				"disallowPackage": [
					[
						"legacyPackages",
						null,
						"sqlite"
					]
				]
			}'
} #end setup

# Test pkgdb scrape with allow_json
@test "pkgdb scrape with allow_json" {
	#disable for now until feature is implemented
	skip "FIXME: disable for now until feature is implemented"
	run pkgdb scrape <(echo "$rules_json") <NIXPKGS >--rules
	assert_success
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.darwin' LIMIT 1"
	assert_output 'darwin'
}

@test "pkgdb scrape with disallow emacs" {
	#disable for now until feature is implemented
	skip "FIXME: disable for now until feature is implemented"
	run pkgdb scrape <(echo "$rules_json") <NIXPKGS >--rules
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.emacs' LIMIT 1"
	assert_output ''
}

@test "pkgdb scrape with both allow_json and disallow_json" {
	#disable for now until feature is implemented
	skip "FIXME: disable for now until feature is implemented"

	run pkgdb scrape <(echo "$rules_json") <NIXPKGS >--rules

	#allowRecursive test
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.darwin' LIMIT 1"
	assert_output 'darwin'
	#disallowRecursive test
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.emacs' LIMIT 1"
	assert_output ''
	#requests should not be found due to disallowRecursive
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.python3Packages.requests' LIMIT 1"
	assert_output ''
	#pip and django should be found allowPackage takes priority over disallowRecursive.
	# that lets us "disable all python310Packages except for ____ (pip and django)"
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.python3Packages.pip' LIMIT 1"
	assert_output 'pip'
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.python3Packages.django' LIMIT 1"
	assert_output 'django'
	#disallowPackage test
	run sqlite3 "$DBPATH" "SELECT attrName FROM Packages      \
    WHERE name = 'legacyPackages.x86_64-linux.sqlite' LIMIT 1"
	assert_output ''
}
```

2024-01-29 13:52 UTC, closed without merging

2024-02-29 13:33 UTC, billlevine commented
Superseded by PR #1095 .