fix(git): catch `push` authentication errors
flox/flox pull request #691
Opened 2023-12-22 11:22 UTC by ysndr

* Add another error detection for failed authentication with git remotes (i.e. floxhub)
* Improve error reporting

closes #686
(cherry picked from commit 784b61704d028231d0d75a6eaa1e11850d85148c)

2023-12-27 20:06 UTC, mkenigs requested changes
question blocking: should this have a test?

2023-12-27 20:06 UTC, mkenigs commented on cli/flox-rust-sdk/src/models/floxmetav2/mod.rs
> +    // If no token is provided, we still set the credential helper
nonblocking
```suggestion
    // If no token is provided, we still set the credential helper and pass an empty string as password
```

2023-12-29 22:37 UTC, ysndr commented
This is still relevant even though #686 was closed by the other PR
This one adds the same error handling to other fig operations and adds tests

2024-01-02 15:35 UTC, ghudgins commented
tested this on the branch...saw an extra error that looked a bit confusing after I said `n` to continue editing

<img width="499" alt="image" src="https://github.com/flox/flox/assets/5465514/d1961647-4ab4-4d52-8b1b-8327aa8f28b5">

2024-01-02 16:22 UTC, ysndr commented
did you run `just flox`?
That error looks a lot like a Justfile error

2024-01-02 16:49 UTC, ghudgins commented
ah yes, I did. then LGTM

2024-01-02 23:44 UTC, mkenigs approved these changes

2024-01-03 00:12 UTC, merged