style: lighter post processing of user facing output
flox/flox pull request #907
Opened 2024-02-01 19:27 UTC by ysndr

* remove bold errors
* remove indentation of following log lines
* add timestamp, file, and line number in `--debug` mode

2024-02-05 14:12 UTC, ysndr commented
I also did some experiments with text wrapping at term width, but removed it for now, pending further clarification.
In my tests it did mess up bats asserts as bats does not ignore line breaks so any asserted output that contains a linebreak fails.
It also wasn't part of the original issue so I'd rather defer this for now

2024-02-06 02:19 UTC, mkenigs requested changes
This is a bit hard for me to review as I'm not familiar with our logging setup, and it makes a lot of changes that aren't explained. Just doing a functional review:
- `flox install does-not-exist` doesn't have `ERROR:` preceding it
- I have to pass `-vv --debug` to see what `pkgdb` commands we're calling, which I don't really want to do.

2024-02-06 10:01 UTC, ysndr commented
For the most part i just tried to make the logging _simpler_ be removing special cases, like the formatter that adds indentation.
since we are not using it in flox (yet?) we can also kick out the "posix" logging (`+ <command>`) for the time being in favor of a more straight forward handler here.

The `--debug` flag now also only influences the _additional_ info (that it also filters seems like a bug to me indeed), and for this approach can likely also just be removed for now.

My eventual goal is have two separate pipelines for logging and communicating.

> `flox install does-not-exist` doesn't have ERROR: preceding it

The headers should be applied at call side IMO, they are not always relevant at the _first_ line of an error, and in non error cases have to be included explicitly anyway -- doing so for both seems to improve consistency

2024-02-06 13:22 UTC, ysndr commented on cli/flox/src/utils/init/logger.rs
> +        Verbosity::Verbose(_) => "trace",
* `-q`: only process errors
* ``: only process info messages or more severe, coming from flox, i.e. user facing logs
* `-v`: process debug messages or more severe, coming from anything flox maintained
* `-vv`:  process trace messages or more severe, coming from anything flox maintained
* `-vvv`:  process trace messages or more severe, coming from anything flox maintained, and debug messages of anything else
* `-vvvv...`: process traces messages of everything

These filters just influence which messages are being processed _at all_, not how.

2024-02-06 13:22 UTC, ysndr commented on cli/flox/src/utils/logger.rs
> +            "log.module_path" => self.0.module = Some(value.to_string()),
these targets are set by the `tracing_log` adapter to of `log`

2024-02-06 16:21 UTC, mkenigs commented
> The `--debug` flag now also only influences the _additional_ info (that it also filters seems like a bug to me indeed), and for this approach can likely also just be removed for now.

Yeah I'd agree it doesn't make a ton of sense at this point. Maybe just drop?
```
> flox --debug install does-not-exist
ERROR 2024-02-06 09:17:04.662360 -07:00 flox/src/main.rs:99:
❌  could not install does-not-exist
ERROR 2024-02-06 09:17:04.662554 -07:00 flox/src/main.rs:127:
❌  could not install does-not-exist
```

> The headers should be applied at call side IMO, they are not always relevant at the _first_ line of an error, and in non error cases have to be included explicitly anyway -- doing so for both seems to improve consistency

👍

2024-02-06 16:25 UTC, mkenigs approved these changes
I would prefer just dropping `--debug` as it doesn't really make sense and will end up in `--help` text and man pages. Up to you whether to do that here

2024-02-06 17:31 UTC, ysndr commented
`--debug` has more effects: with `--debug` flox won't delete the temp dirs it creates so you can inspect them or rerun commands.

Though that's all rather internal debuggy tools, so lets just hide `--debug` for now

2024-02-06 17:37 UTC, mkenigs approved these changes

2024-02-06 18:04 UTC, mkenigs approved these changes

2024-02-06 18:58 UTC, merged