fix: catalog parsing for flake upgrades
flox/flox pull request #91
Opened 2023-06-06 08:59 UTC by limeytexan

This commit partially reverts commit 7d16e9bb which broke the ability to detect available catalog entry upgrades and fixes the ability to detect available flake upgrades. It is being rolled out as a hotfix to flox-prerelease as this is currently breaking the functionality of `flox upgrade` in the majority of cases.

## Checks

- [x] All tests pass.
- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] I have accepted the flox [Contributor License Agreement](../blob/main/.github/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](../blob/main/.github/CONTRIBUTORS.csv) file by way of this pull request or one done previously.

## Release Notes

* Fixed bug introduced with #74 which affected the ability to upgrade packages with `flox upgrade`.

2023-06-12 18:38 UTC, mkenigs requested changes

2023-06-12 18:38 UTC, mkenigs commented on flox-bash/lib/diff-catalogs.jq
> +      "ERROR: encountered object of type \(type)" | halt_error(1)
```suggestion
      # We got to a leaf before finding a package, so there was never a valid catalog entry.
      "Internal error: invalid catalog data" | halt_error(1)
```

2023-06-14 12:39 UTC, limeytexan commented on flox-bash/lib/diff-catalogs.jq
> +  has("build") and has("element") and has("eval") and has("version");
Thanks. Amending accordingly.

```suggestion
  (has("type") and .["type"] == "catalogRender") or (has("element") and has("eval") and has("version"));
```

2023-06-14 12:39 UTC, limeytexan commented on flox-bash/lib/diff-catalogs.jq
> +def isFlakePackage:
```suggestion
def isPackage:
```

2023-06-14 12:40 UTC, limeytexan commented on flox-bash/lib/diff-catalogs.jq
> +  );
```suggestion
  isPackage and has("publish_element");
```

2023-06-14 12:42 UTC, limeytexan commented on flox-bash/lib/diff-catalogs.jq
> +  );
Done.

2023-06-14 12:43 UTC, limeytexan commented
@mkenigs thanks for the review - I've updated accordingly can you give it one final review? Thanks.

2023-06-14 13:35 UTC, mkenigs approved these changes

2023-06-15 09:07 UTC, ysndr commented
@limeytexan is this in for the release today?

2023-06-15 09:35 UTC, limeytexan commented
Thanks for flagging - yes let's go ahead and roll this one in.

2023-06-15 09:41 UTC, merged