feat: add Message abstraction
flox/flox pull request #947
Opened 2024-02-07 13:47 UTC by ysndr

We are currently using a mix of `println!, `eprintln!`, `log::info!`, `log::error!`
to display _messages_ to users on the CLI.

* `println!` => processable output.
* `log::error!` => error messages, prefixed with `ERROR:`
* `eprintln!` and `log::info` => other user facing messages without or limited processing

Using `log` for user output is suboptimal since `log` will do double duty
for logging and messaging.
While `log::error` applied styling and was used semantically correct,
where we wanted to express _errors_, `log::info` is overloaded for all kinds of messages
and thus requires styling to be applied by the caller.

The proposed `Message` object separates message content and semantic styling.
A message is written, then styled, then shown.

Being separated from the the `log` level naming conventions,
`Message` can provide multiple possible semantic stylings according to the style guide:

* MessageKind::Error   => Error messages: "❌ ERROR:",
* MessageKind::Created => Creation: ✨ ",
* MessageKind::Deleted => Removing something: "🗑️ ",
* MessageKind::Updated => Adding something to something existing: "✅ ",
* MessageKind::Warning => Warning about something: "⚠️ ",

As a layer on top of `eprintln!` it also allows for post processing,
e.g. word wrapping at terminal or fixed width, clearing of ANSI sequences,
respecting `--quiet` etc.

## Examples

```
let message = "Some String";
let message = Message::warn(message);

assert_eq!(message.to_string(), "⚠️  Some String");
```

```
let message = "Another String";

// DisplayExt provides conversions methods for everything that implements `Display`
let message = message.created();
assert_eq!(message.to_string(), "✨  Some String");
```

```
// use `show()` to print to stderr
"printed message".updated().show()
```## Proposed Changes

2024-02-07 18:56 UTC, zmitchell requested changes
I think we can go with a much more lightweight implementation that doesn't require this level of abstraction. At the end of the day all we need to do is prepend a small string to the provided message. This could be accomplished with a small collection of functions like `warning`, `error`, etc that simply prepend the necessary string. This would be easier to maintain.

On the grounds of readability, calling `"foo".<method>()` as a means of turning it into a displayed message is confusing because `error` becomes overloaded with Rust error handling, and `created`, `deleted`, and `updated` look like they're doing some operation on the string. For example, it's hard to know what `"foo".created()` means unless you're familiar with this particular piece of code. I also suspect that it would be confusing for the non-Rust developers to see this.

All in all, I think just a few functions that format and print messages would be more maintainable and easier to read precisely because it's brain dead simple.

2024-02-07 19:09 UTC, ysndr commented
I mean these are effectively just functions, the string/displayExt stuff was there look familiar wrt to stylize from Crossterm, colored or other text styling crates that do something similar.

We can forego those and use `Message::{styles}(“string”)` only.
I did want to ensure the printing is done by Message though, so any logic pertaining the terminal capabilities width color …) is in one place

2024-02-07 19:26 UTC, mkenigs commented
> We can forego those and use `Message::{styles}(“string”)` only. I did want to ensure the printing is done by Message though, so any logic pertaining the terminal capabilities width color …) and silencing non error messages with —quiet. is in one place

I think we can accomplish all of that with `print_stdout()` and `print_stderr()` functions. I think having one for error probably also makes sense, but I'm not sure we need one for each of the emojis, although I don't feel super strongly on that one.

Just so I understand, why is it important to keep output that we want to go to stderr and logging separate?

2024-02-07 23:37 UTC, zmitchell commented
> the string/displayExt stuff was there look familiar wrt to stylize from Crossterm, colored or other text styling crates that do something similar.

I don't think we need that

> We can forego those and use Message::{styles}(“string”) only.

I don't see the point of that over a bare function though.

> I think we can accomplish all of that with print_stdout() and print_stderr() functions.

I mostly agree.

> but I'm not sure we need one for each of the emojis, although I don't feel super strongly on that one.

I'd prefer we have dedicated functions for message types that can appear in multiple places e.g. `print_error` so that we don't have to change things in multiple places. For things that only appear in one place like installing a package we can go with a one-off `print_stdout` call.

2024-02-08 13:46 UTC, ysndr commented
> I'd prefer we have dedicated functions for message types that can appear in multiple places e.g. print_error so that we don't have to change things in multiple places. For things that only appear in one place like installing a package we can go with a one-off print_stdout call.

I'd really like us having a single interface for messages, that makes it explicit what _kind_ of message we print if that is 
```rust 
fn print_error(&str), fn print_created(&str), ...
fn message(kind: MessageKind, &str)
..
```

2024-02-08 17:05 UTC, mkenigs commented
> I'd really prefer us having a single interface for messages, that makes it explicit what _kind_ of message we print if that is
> 
> ```rust
> fn print_error(&str), fn print_created(&str), ...
> fn message(kind: MessageKind, &str)
> ..
> ```
> 
> or this stateful one here, I don't really mind. I'd just be consistent and explicit

I think
```
fn print_error(msg: &str) {
  print_stderr(format!("❌  {msg}")
}
```
is more readable than
```
fn print_error(msg: &str) {
  message(MessageKind::Error, msg)
}
```

2024-02-08 17:08 UTC, mkenigs commented
> You want to likely style logs differently, or route them differently e.g. write them to a log file rather than completely silence them.
> 
> Messages _can also_ be logged in addition, but simply displaying them should prob be separate from processing logs

Couldn't you handle both of those cases in the logger? Style it a certain way if it's info && headed to stderr? And style it another way if it's headed to a log file? Does that just not feel clean to you?

2024-02-08 18:07 UTC, ysndr commented
I meant `print_error("something")` and `message(Error, "something")` not combined as you set them.
Using emojis inline is great, until the emojis get rather ambiguous, some are double width and some single width,...

---

when using log `info` as the primary interface it's weird to separate actual logging messages from ui messages.
We could distinguish by splitting between `log::*` and `tracing::log` or passing a specific target, but i'd still like that to be an internal detail

2024-02-08 22:57 UTC, zmitchell commented
> Messages _can_ also be logged in addition, but simply displaying them should prob be separate from processing logs

I'm not sure we have many cases where this actually happens, and for the few cases where it does happen we can just have a duplicate line:
```
let msg = "something";
print_stdout(msg);
log::info!(msg);
```
This keeps the content the same and the responsibilities separate since the styling can actually be applied in `print_stdout` and the unstyled output is sent through to the logs.

Either way, I don't think this is a common case and I'd rather optimize for readability via a collection of `print_*` functions.

You've gotten two reviews that both think a stateless `print_*` solution is preferable, so do we want to spend much more time on this?

2024-02-09 17:04 UTC, zmitchell approved these changes

2024-02-09 18:30 UTC, ghudgins approved these changes
LGTM from product side

2024-02-09 18:43 UTC, zmitchell commented
@ysndr somehow `jq` wasn't found and caused the test failure

2024-02-12 10:50 UTC, merged