style(list): print a warning if environment is empty
flox/flox pull request #987
Opened 2024-02-12 14:51 UTC by ysndr

fixes #930

2024-02-12 16:07 UTC, ghudgins commented
looks good to me on the branch

2024-02-12 16:15 UTC, ysndr commented
@ghudgins i figured this can also address #887, i extended the warning with a hint to `flox list --config`

2024-02-12 16:18 UTC, ghudgins commented
great idea. agreed

2024-02-13 18:19 UTC, mkenigs requested changes

2024-02-13 18:19 UTC, mkenigs commented on cli/flox/src/commands/environment.rs
> +                No packages are installed for tour current system ('{system}').
```suggestion
                No packages are installed for your current system ('{system}').
```

2024-02-13 18:25 UTC, mkenigs approved these changes
nonblocking: add a test

2024-02-13 19:23 UTC, merged