Tomberek.non flake
flox/flox pull request #999
Opened 2024-02-13 14:10 UTC by tomberek

## Proposed Changes

- Trim lockfile
- better handling of release suffix

## Release Notes

2024-02-13 14:13 UTC, garbas approved these changes

2024-02-14 16:55 UTC, tomberek reviewed
@aakropotkin

2024-02-14 18:35 UTC, rossturk requested changes

2024-02-14 18:35 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - The FloxHub service and its associated commands more broadly available to anyone with a valid GitHub account. Try the commands to sign up-- `flox push`, `flox pull`, `flox auth login`.
```suggestion
 - The FloxHub service and its associated commands are more broadly available to anyone with a valid GitHub account. Try the commands to sign up-- `flox push`, `flox pull`, `flox auth login`.
```

2024-02-14 18:35 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> +This release contains **breaking changes in the Flox CLI** and FloxHub service. You are responsible for recreating environments created in 0.3.6 and prior versions. If you rely on a command that has
```suggestion
This release contains **breaking changes in the Flox CLI** and FloxHub service. You are responsible for recreating environments created in 0.3.6 and prior versions. If you rely on a command that has been removed, we recommend that you wait to upgrade until support is added. We'd love to hear from you on our discourse forum if you have questions.
```

2024-02-14 18:35 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - Several deprecated sub commands were removed. Notably the `build` and `publish` command is no longer in Flox CLI. We have plans to return the build and publish features to Flox in the future. Cons
```suggestion
 - Several deprecated subcommands were removed. Notably the `build` and `publish` commands are no longer available in Flox CLI. We have plans to return the build and publish features to Flox in the future. Consult the `--help` or `man flox` for a full list of supported commands.
```

2024-02-14 18:35 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - The Flox catalog that powers search and install is now tied to nixpkgs `23.11` stable branch. We have short term plans to expand the library of software in the Flox Catalog. `update` and `upgrade`
```suggestion
 - The Flox catalog that powers search and install is now tied to NixPkgs `23.11` stable branch. We have short term plans to expand the library of software in the Flox Catalog. `update` and `upgrade` will advance metadata index and software versions along the stable `23.11` branch.
```

2024-02-14 21:28 UTC, rossturk requested changes

2024-02-14 21:28 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - Flox enviornments support multiple architectures without having to create multiple environments.
```suggestion
 - Flox environments support multiple architectures without having to create multiple environments. 
```

2024-02-14 21:28 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - Flox stores environment definition in a `.flox` folder in the current working directory by default.
```suggestion
 - Flox now stores environment definition in a `.flox` folder in the current working directory by default.
```

2024-02-14 21:28 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - Environments are now delcared in a `manifest.toml` file embedded inside the `.flox` folder. `flox edit` will allow edits and validate changes made.
```suggestion
 - Environments are now declared in a `manifest.toml` file located inside the `.flox` folder. `flox edit` will allow edits and validate changes made.
```

2024-02-14 21:28 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - The FloxHub service and its associated commands are more broadly available to anyone with a valid GitHub account. Try the commands to sign up-- `flox push`, `flox pull`, `flox auth login`.
```suggestion
 - The FloxHub service and its associated commands are now available to anyone with a valid GitHub account. These commands will direct you to sign up: `flox push`, `flox pull`, `flox auth login`.
```

2024-02-14 21:28 UTC, rossturk commented on doc/release-notes/rl-0.9.0.md
> + - The Flox catalog that powers search and install is now tied to NixPkgs `23.11` stable branch. We have short term plans to expand the library of software in the Flox Catalog. `update` and `upgrade`
```suggestion
 - The Flox catalog that powers search and install is now tied to the NixPkgs `23.11` stable branch. We have short term plans to expand the library of software in the Flox Catalog. Currently `update` and `upgrade` will advance metadata index and software versions along the stable `23.11` branch.
```

2024-02-14 22:33 UTC, merged